# settings for analysis of B cell subpopulations

# -- data loading paths --
path_unsup_training: './data/training'
path_sup_training: './data/training_supervised'
path_concat: './data/concat_in'
path_preselect: './data/preselect'
path_inference: './data/testing'
path_models: './data/models'
# -- data saving paths
save_path_unsup_training: './results/unsupervised_training'
save_path_sup_training: './results/supervised_training'
save_path_concat: './results/concat_out'
save_path_preselect: './results/preselection'
save_path_inference: './results/inference'

# -- settings for preprocessing --
csv_out_english: False

# -- settings for training and inference --
trainchannels: ['FSC-A', 'SSC-A', 'CD19', 'CD3', 'CD38', 'CD45']
# e.g. Julia Scholz ['FSC-A', 'SSC-A', 'CD19', 'CD3', 'CD20', 'CD45', 'CD38', 'CD10', 'IgD', 'CD24', 'CD27']
SOM_dim:
  - 15
  - 15
SOM_epochs: 100
val_range: [0, 262144] # 262144 for BD, 1048576 for Coulter Navios
trafo_arcsinh: True # if False set cut offs for log trafo
arcsinh_div: 150  # 150 recommended for BD files
# channel_name_to_cutoff: {'FS INT': 50000, etc} # define if arcsinh = false
lin_trafo_FSSS: false # applies linear trafo instead of log or arcsinh for FS and SS

# -- only relevant for training --
calcTSNE: True # (True is always recommended for unsupervised training)
size_per_sample: 5000 # maximum size. refers to events per file(s), not per single samples of already concatenated files

# -- settings only relevant for preselection script ---
size_pop_1: 1000 # maximum size per population
size_pop_2: 7000
size_pop_3: 8000
include_predict_columns: False

# -- settings only relevant for inference, irrelevant for training scripts --
max_rows_per_batch: 500000 # maximum number of lines to read in at once for inference. # 2 Mio is reasonable
show_SOM: True # procedure is fast in inference
calcchannels: ['CD20', 'CD45'] # if fluorescence intensity per channel and population. population sizes are always calculated
calc_populations: [1,2,3] # Optional list of MLP population labels for which to compute calcchannel medians.
         # Set to null or omit to use all predicted populations.