# settings for Sysmex data files
trainchannels: ['Side Scatter Signal', 'Side Fluorescence Signal', 'Forward Scatter Signal', 'Forward Scatter Pulse Width Signal']
# WDF: ['Side Scatter Signal', 'Side Fluorescence Signal', 'Forward Scatter Signal', 'Forward Scatter Pulse Width Signal']
# WDF short names: ['SSC', 'SFL', 'FSC', 'FSCW']
size_per_sample: 20000
SOM_dim:
  - 10
  - 10
SOM_epochs: 100
val_range: [0, 256] # 262144 for BD, 1048576 for Coulter Navios, 256 for Sysmex
trafo_arcsinh: True # if False set cut offs for log trafo
arcsinh_div: 30  # 30 recommended for Sysmex files
calcTSNE: True # if TSNE is calculated. Set to False to save time during script test