# settings for AL samples
trainchannels: ['FS INT', 'SS INT', '45-CO']
# AL1: ['FS INT', 'SS INT', '15-FITC', '13-PE', '34-ECD', '117-PC5.5', '33-PC7', '2-APC', 
#  '7-APC-AF700', 'HLADR-PB', '45-CO'] 'APC-AF750'
size_per_sample: 5000 # maximum size. refers to events/file(s), not /single samples of already concatenated files
SOM_dim:
  - 20
  - 20
SOM_epochs: 100
val_range: [0, 1048576] # 262144 for BD, 1048576 for Coulter Navios
trafo_arcsinh: True # if False set cut offs for log trafo
arcsinh_div: 300  # 150 to 300 recommended for Navios files
channel_name_to_cutoff: {'FS INT': 50000, 'SS INT': 10000, '15-FITC': 100, '13-PE': 300, '33-PC7': 200, '2-APC': 200, 
  '7-APC-AF700': 200, '34-ECD': 200, '117-PC5.5': 200, 'HLADR-PB': 200, '45-CO': 200} # define if arcsinh = false
lin_trafo_FSSS: false # applies linear trafo instead of log or arcsinh for FS and SS
calcTSNE: True # Only relevant for unsupervised training. for inference, check compute_dim_red below
# -- the following only relevant for inference, irrelevant for training scripts --
compute_dim_red: True # set to false for inference, if only tabular results are of interest
calcchannels: ['13-PE', '34-ECD', '117-PC5.5', '33-PC7']
calc_populations: [1,2,3,4,5] # Optional list of MLP population labels for which to compute calcchannel medians.
         # Set to null or omit to use all predicted populations.